(()=>{
const IMPORTED_ROWS_KEY='scheduleImportedRows',SAFETY_BADGES_KEY='scheduleSafetyBadges',SAFETY_XLSX_URL='https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js',LIVE_REFRESH_MS=60000;
let importedRows=readImportedRows(),liveRows=Array.isArray(data)?data.slice():[];
let safetyXlsxPromise;
const byId=id=>document.getElementById(id);
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));}
function timeValue(value){const match=String(value||'').match(/T(\d{2}):(\d{2})/);return match?match[1]+':'+match[2]:String(value||'');}
function dateValue(value){const parts=String(value||'').split('/');return parts.length===3?parts[2]+'-'+parts[1].padStart(2,'0')+'-'+parts[0].padStart(2,'0'):String(value||'').slice(0,10);}
function todayValue(){const now=new Date();return now.getFullYear()+'-'+String(now.getMonth()+1).padStart(2,'0')+'-'+String(now.getDate()).padStart(2,'0');}
function periodValue(value){const match=String(value||'').match(/T(\d{2}):/),hour=match?Number(match[1]):0;return hour>=5&&hour<12?'AM':hour>=12&&hour<18?'PM':'Nights';}
function cleanDateTime(value){const match=String(value||'').match(/(\d{4}-\d{2}-\d{2}T\d{2}:\d{2})/);return match?match[1]:String(value||'').trim();}
function normaliseRows(rows){if(!Array.isArray(rows))throw Error('Schedule data is not a list of shifts.');return rows.filter(row=>row&&typeof row==='object').map(row=>{const location=String(row.location||'').trim(),start=cleanDateTime(row.start);return {name:String(row.name||'').trim(),location,type:String(row.type||'')||(location.toLowerCase().includes('service provider')?'CDC':'DC'),date:String(row.date||'').trim(),start,end:cleanDateTime(row.end),hours:Number(row.hours)||0,role:String(row.role||'').trim(),period:String(row.period||'')||periodValue(start)};});}
function shiftIdentity(row){return [String(row.name||'').trim().toLowerCase(),dateValue(row.date)].join('||');}
function datesIn(rows){return new Set(rows.map(row=>dateValue(row.date)).filter(Boolean));}
function mergeRows(...sets){const rows=new Map();sets.flat().forEach(row=>{if(row.name&&row.date)rows.set(shiftIdentity(row),row);});return [...rows.values()];}
function replaceImportedDates(existing,incoming){const dates=datesIn(incoming);return mergeRows(existing.filter(row=>!dates.has(dateValue(row.date))),incoming);}
function mergedSchedule(){const dates=datesIn(importedRows);return mergeRows(liveRows.filter(row=>!dates.has(dateValue(row.date))),importedRows);}
function readImportedRows(){try{const stored=localStorage.getItem(IMPORTED_ROWS_KEY);return stored?normaliseRows(JSON.parse(stored)):[];}catch(error){console.error('Unable to read imported schedules',error);return [];}}
function saveImportedRows(rows){try{localStorage.setItem(IMPORTED_ROWS_KEY,JSON.stringify(rows));}catch(error){throw Error('Imported schedules could not be saved in this browser. Clear older imported schedules and try again.');}}
function showError(message){const error=byId('error');error.textContent=message||'';error.hidden=!message;}
function syncImportStatus(){const count=importedRows.length,clearButton=byId('clearImportedSchedules');byId('fileName').textContent=count?'schedule.json + '+count.toLocaleString()+' imported shifts':'schedule.json';if(clearButton)clearButton.disabled=!count;}
function applyMergedData(){data=mergedSchedule();setRoleOptions();syncImportStatus();renderOverview();}
function parseCsv(text){const rows=[];let row=[],cell='',quoted=false;for(let index=0;index<text.length;index++){const character=text[index],next=text[index+1];if(quoted){if(character==='"'&&next==='"'){cell+='"';index++;}else if(character==='"')quoted=false;else cell+=character;}else if(character==='"')quoted=true;else if(character===','){row.push(cell);cell='';}else if(character==='\n'){row.push(cell);rows.push(row);row=[];cell='';}else if(character!=='\r')cell+=character;}if(cell.length||row.length){row.push(cell);rows.push(row);}return rows;}
function parseUploadedCsv(text){const rows=parseCsv(text);if(!rows.length)throw Error('The file is empty.');const headers=rows[0].map(value=>String(value).replace(/^\ufeff/,'').trim().toLowerCase()),indexOf=header=>headers.indexOf(header),columns={name:indexOf('shift employee name'),location:indexOf('shift employee home location name'),date:indexOf('shift date'),start:indexOf('scheduled start time'),end:indexOf('scheduled end date'),hours:indexOf('scheduled hours'),role:headers.includes('workrole')?indexOf('workrole'):indexOf('work role')};if(Object.values(columns).some(index=>index<0))throw Error('Missing an expected schedule export column.');return rows.slice(1).filter(row=>row.some(value=>String(value).trim())).map(row=>{const location=String(row[columns.location]||'').trim(),start=cleanDateTime(row[columns.start]);return {name:String(row[columns.name]||'').trim(),location,type:location.toLowerCase().includes('service provider')?'CDC':'DC',date:String(row[columns.date]||'').trim(),start,end:cleanDateTime(row[columns.end]),hours:Number(String(row[columns.hours]||'').replace(',','.'))||0,role:String(row[columns.role]||'').trim(),period:periodValue(start)};}).filter(row=>row.name&&row.date);}
function readScheduleFile(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=event=>{try{resolve(parseUploadedCsv(event.target.result));}catch(error){reject(error);}};reader.onerror=()=>reject(Error('The browser could not read '+file.name+'.'));reader.readAsText(file);});}
async function importScheduleFiles(files){const selected=[...files].filter(file=>file&&file.name);if(!selected.length)return;try{const imported=(await Promise.all(selected.map(readScheduleFile))).flat();if(!imported.length)throw Error('The selected files contain no shifts.');const nextImported=replaceImportedDates(importedRows,imported);saveImportedRows(nextImported);importedRows=nextImported;showError('');applyMergedData();byId('status').textContent=selected.length+' schedule file'+(selected.length===1?'':'s')+' merged. '+importedRows.length.toLocaleString()+' imported shifts available.';}catch(error){showError('Upload error: '+error.message);byId('status').textContent='The current schedule is still loaded.';}}
function localDateKey(date){return date.getFullYear()+'-'+String(date.getMonth()+1).padStart(2,'0')+'-'+String(date.getDate()).padStart(2,'0');}
function selectedWeek(anchor){const date=new Date(anchor+'T00:00'),start=new Date(date);start.setDate(date.getDate()-date.getDay());const end=new Date(start);end.setDate(start.getDate()+6);return {start:localDateKey(start),end:localDateKey(end)};}
function dateInView(rowDate,anchor,view){if(!anchor)return true;if(view==='day'||!view)return rowDate===anchor;if(view==='month')return rowDate.slice(0,7)===anchor.slice(0,7);const week=selectedWeek(anchor);return rowDate>=week.start&&rowDate<=week.end;}
function reportDay(row){const date=new Date(dateValue(row.date)+'T00:00'),weekday=date.toLocaleDateString('en-GB',{weekday:'short'}),period=row.period||periodValue(row.start);return weekday+' '+period;}
function csvCell(value){return '"'+String(value??'').replace(/"/g,'""')+'"';}
function syncWeeklyReportAction(){const button=byId('downloadWeeklyReport');if(button)button.disabled=!byId('date').value;}
function missingReportDates(rows,week){const dates=new Set(rows.map(row=>dateValue(row.date))),missing=[],start=new Date(week.start+'T00:00');for(let offset=0;offset<7;offset++){const date=new Date(start);date.setDate(start.getDate()+offset);const key=localDateKey(date);if(!dates.has(key))missing.push(date.toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short'}));}return missing;}
function reportDateTime(date){return localDateKey(date)+'T'+String(date.getHours()).padStart(2,'0')+':'+String(date.getMinutes()).padStart(2,'0');}
function reportPeriod(date){const hour=date.getHours();return hour>=6&&hour<14?'AM':hour>=14&&hour<22?'PM':'Nights';}
function nextReportBoundary(date){const boundary=new Date(date),hour=boundary.getHours();if(hour<6)boundary.setHours(6,0,0,0);else if(hour<14)boundary.setHours(14,0,0,0);else if(hour<22)boundary.setHours(22,0,0,0);else{boundary.setDate(boundary.getDate()+1);boundary.setHours(6,0,0,0);}return boundary;}
function splitDcReportRow(row){const start=new Date(row.start),end=new Date(row.end),day=new Date(dateValue(row.date)+'T00:00').getDay();if(row.type!=='DC'||day===0||day===6||Number.isNaN(start.getTime())||Number.isNaN(end.getTime())||end<=start)return [row];const segments=[];let segmentStart=start;while(segmentStart<end){const boundary=nextReportBoundary(segmentStart),segmentEnd=boundary<end?boundary:end;segments.push({...row,date:localDateKey(segmentStart),start:reportDateTime(segmentStart),end:reportDateTime(segmentEnd),period:reportPeriod(segmentStart)});segmentStart=segmentEnd;}return segments;}
function downloadWeeklyReport(){const anchor=byId('date').value,group=byId('group').value;if(!anchor){showError('Select a shift date before downloading the weekly shift report.');return;}const week=selectedWeek(anchor),sourceRows=data.filter(row=>row.name&&row.date&&(!group||row.type===group)&&dateInView(dateValue(row.date),anchor,'week')),rows=(group==='DC'?sourceRows.flatMap(splitDcReportRow):sourceRows).sort((left,right)=>String(left.name).localeCompare(String(right.name))||dateValue(left.date).localeCompare(dateValue(right.date))||String(left.start).localeCompare(String(right.start)));if(!rows.length){showError('No '+(group?group+' ':'')+'scheduled shifts are available for '+week.start+' to '+week.end+'.');return;}const csv=[['Employee Name','Core Skill','Start','End','Day'],...rows.map(row=>[row.name,row.role,timeValue(row.start),timeValue(row.end),reportDay(row)])].map(row=>row.map(csvCell).join(',')).join('\r\n')+'\r\n',link=document.createElement('a'),missingDates=missingReportDates(rows,week);link.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));link.download='weekly-shift-report-'+week.start+'-to-'+week.end+'.csv';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(link.href),0);showError('');byId('status').textContent='Downloaded '+rows.length.toLocaleString()+' '+(group?group+' ':'')+'shift'+(rows.length===1?'':'s')+' for '+week.start+' to '+week.end+'.'+(missingDates.length?' The loaded schedule has no shifts for '+missingDates.join(', ')+'.':'');}
function baseRows(){const query=byId('search').value.trim().toLowerCase(),group=byId('group').value,date=byId('date').value,view=byId('dateView').value,roles=[...byId('role').selectedOptions].map(option=>option.value);return data.filter(row=>allowedRoles.includes(row.role)&&(!query||row.name.toLowerCase().includes(query))&&(!group||row.type===group)&&dateInView(dateValue(row.date),date,view)&&(!roles.length||roles.includes(row.role)));}
function updatePeriodOptions(){const period=byId('period'),current=period.value,rows=baseRows(),counts={AM:0,PM:0,Nights:0};rows.forEach(row=>{if(counts[row.period]!==undefined)counts[row.period]++;});period.innerHTML='<option value="">All shift patterns ('+rows.length+')</option>'+['AM','PM','Nights'].map(value=>'<option value="'+value+'">'+value+' ('+counts[value]+')</option>').join('');period.value=['','AM','PM','Nights'].includes(current)?current:'';}
function currentFilters(){const labels=[],roles=[...byId('role').selectedOptions].map(option=>option.value),view=byId('dateView').value;if(byId('search').value.trim())labels.push('name search');if(byId('group').value)labels.push(byId('group').value);if(roles.length)labels.push(roles.length===1?roles[0]:roles.length+' roles');if(byId('period').value)labels.push(byId('period').value);if(byId('date').value)labels.push(view?view+' of '+byId('date').value:byId('date').value);return labels;}
function overviewCard(row){const color=roleColors[row.role]||'default',key=encodeURIComponent([row.name,row.date,row.start,row.end,row.role].join('||')),name=escapeHtml(row.name);return '<li><article class="card card-'+color+'"><div style="display:flex;justify-content:space-between;gap:6px;align-items:flex-start"><div class="name">'+name+'</div><button class="remove-btn" type="button" data-remove="'+key+'" aria-label="Remove '+name+' from this shift">Remove</button></div><div class="role role-'+color+'">'+escapeHtml(row.role||'Work role not specified')+'</div><div class="times"><div class="time"><small>Start</small><b>'+timeValue(row.start)+'</b></div><div class="time"><small>End</small><b>'+timeValue(row.end)+'</b></div></div><div class="meta"><span>'+escapeHtml(row.period)+'</span><span>'+escapeHtml(row.hours)+' hrs</span></div></article></li>';}
function renderOverview(){updatePeriodOptions();if(typeof updateAbsenceSummary==='function')updateAbsenceSummary();const period=byId('period').value,rows=baseRows().filter(row=>!period||row.period===period).filter(row=>!removed[[row.name,row.date,row.start,row.end,row.role].join('||')]),people=new Set(rows.map(row=>row.name)),hours=rows.reduce((total,row)=>total+(Number(row.hours)||0),0),labels=currentFilters();byId('kpis').innerHTML=[['People',people.size,'indigo'],['Shift count',rows.length,'sky'],['Total hours',hours.toFixed(1),'green'],['Shift period',period||'All','violet']].map(item=>'<div class="kpi"><div class="label">'+item[0]+'</div><div class="value '+item[2]+'">'+item[1]+'</div></div>').join('');byId('count').textContent=rows.length.toLocaleString()+' shift'+(rows.length===1?'':'s');byId('cards').innerHTML=rows.slice().sort((left,right)=>String(left.start).localeCompare(String(right.start))).map(overviewCard).join('');byId('empty').hidden=Boolean(rows.length);byId('filterSummary').textContent=rows.length.toLocaleString()+' shift'+(rows.length===1?'':'s')+' for '+(labels.length?labels.join(', '):'all teams, roles, periods, and dates')+'.';byId('clear').disabled=!labels.length;syncWeeklyReportAction();}
function clearFilters(){byId('search').value='';byId('group').value='';byId('period').value='';byId('date').value='';byId('dateView').value='';[...byId('role').options].forEach(option=>option.selected=false);renderOverview();byId('search').focus();}
function normaliseSafetyText(value){return String(value??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().replace(/\s+/g,' ').toLowerCase();}
function safetyBadgeData(){try{const stored=localStorage.getItem(SAFETY_BADGES_KEY),data=stored?JSON.parse(stored):null;return data&&typeof data==='object'?data:null;}catch(error){console.error('Unable to read safety badges',error);return null;}}
function safetyNamesFromSheet(workbook,sheetName){const rows=XLSX.utils.sheet_to_json(workbook.Sheets[sheetName],{header:1,defval:''}),headerIndex=rows.findIndex(row=>row.some(cell=>normaliseSafetyText(cell)==='name'));if(headerIndex<0)return [];const nameColumns=rows[headerIndex].map((cell,index)=>normaliseSafetyText(cell)==='name'?index:-1).filter(index=>index>=0),names=new Set();rows.slice(headerIndex+1).forEach(row=>nameColumns.forEach(column=>{const name=String(row[column]??'').trim();if(name&&!normaliseSafetyText(name).startsWith('date reviewed'))names.add(name);}));return [...names];}
function safetySheets(workbook,pattern){return workbook.SheetNames.filter(name=>pattern.test(name));}
function loadSafetyXlsx(){if(window.XLSX)return Promise.resolve(window.XLSX);if(!safetyXlsxPromise)safetyXlsxPromise=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src=SAFETY_XLSX_URL;script.async=true;script.onload=()=>window.XLSX?resolve(window.XLSX):reject(Error('The spreadsheet reader did not load correctly.'));script.onerror=()=>reject(Error('The spreadsheet reader could not be loaded. Check your network connection and try again.'));document.head.append(script);});return safetyXlsxPromise;}
async function parseSafetyWorkbook(file){await loadSafetyXlsx();const workbook=XLSX.read(await file.arrayBuffer(),{type:'array'}),firstAidSheets=safetySheets(workbook,/first\s*aid/i),fireSheets=safetySheets(workbook,/fire\s*marshal/i),heightSheets=safetySheets(workbook,/\bwah\b|working\s*at\s*height/i);if(!firstAidSheets.length||!fireSheets.length||!heightSheets.length)throw Error('The workbook must include First Aid, Fire Marshals, and WAH sheets.');const names=sheets=>[...new Set(sheets.flatMap(sheet=>safetyNamesFromSheet(workbook,sheet)))];return {firstAid:names(firstAidSheets),fireMarshal:names(fireSheets),workingAtHeight:names(heightSheets)};}
function syncSafetyImportStatus(){const status=byId('safetyBadgeStatus'),clearButton=byId('clearSafetyBadges'),badges=safetyBadgeData();if(!status)return;const total=badges?badges.firstAid.length+badges.fireMarshal.length+badges.workingAtHeight.length:0;status.textContent=badges?'Safety badges: '+badges.firstAid.length+' first aid, '+badges.fireMarshal.length+' fire marshal, '+badges.workingAtHeight.length+' working at height.':'No safety badge list loaded.';if(clearButton)clearButton.disabled=!total;}
async function importSafetyWorkbook(file){if(!file)return;try{const badges=await parseSafetyWorkbook(file);localStorage.setItem(SAFETY_BADGES_KEY,JSON.stringify(badges));showError('');syncSafetyImportStatus();byId('status').textContent='Safety badges imported from '+file.name+'.';}catch(error){showError('Safety upload error: '+error.message);}}
function addSafetyControls(){const panel=byId('upload').closest('.panel'),heading=panel.querySelector('.panel-heading');if(!byId('safetyUpload')){const label=document.createElement('label'),input=document.createElement('input'),clearButton=document.createElement('button'),status=document.createElement('div');label.className='clear';label.htmlFor='safetyUpload';label.textContent='Upload safety badges';input.id='safetyUpload';input.className='visually-hidden';input.type='file';input.accept='.xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';clearButton.id='clearSafetyBadges';clearButton.className='clear';clearButton.type='button';clearButton.textContent='Clear safety badges';status.id='safetyBadgeStatus';status.className='data-note hint';status.setAttribute('role','status');status.setAttribute('aria-live','polite');heading.append(label,input,clearButton);panel.append(status);input.addEventListener('change',event=>{const [file]=event.target.files;importSafetyWorkbook(file);event.target.value='';});clearButton.addEventListener('click',()=>{if(confirm('Clear all imported safety badges from this browser?')){localStorage.removeItem(SAFETY_BADGES_KEY);syncSafetyImportStatus();byId('status').textContent='Safety badges cleared.';}});}syncSafetyImportStatus();}
function addControls(){const dateField=byId('date').closest('.field'),uploadRow=byId('upload').closest('.panel').querySelector('.panel-heading'),filterHeading=byId('filters').closest('.panel').querySelector('.panel-heading');if(!byId('dateView')){const field=document.createElement('div');field.className='field';field.innerHTML='<label for="dateView">Date view</label><select id="dateView"><option value="">All scheduled dates</option><option value="day">Selected day</option><option value="week">Selected week</option><option value="month">Selected month</option></select>';dateField.insertAdjacentElement('afterend',field);}if(!byId('weeklyReportHelp')){const help=document.createElement('span');help.id='weeklyReportHelp';help.className='visually-hidden';help.textContent='Choose a shift date to download all loaded schedules for that Sunday to Saturday week. The selected team affects the report; work role, shift period, and date-view filters do not. DC reports split Monday to Friday shifts at 06:00, 14:00, and 22:00.';filterHeading.append(help);}if(!byId('downloadWeeklyReport')){const button=document.createElement('button');button.id='downloadWeeklyReport';button.className='clear';button.type='button';button.textContent='Download weekly shift report';button.disabled=true;button.title='Select a shift date to enable this report.';button.setAttribute('aria-describedby','weeklyReportHelp');filterHeading.querySelector('#clear').insertAdjacentElement('beforebegin',button);button.addEventListener('click',downloadWeeklyReport);}if(!byId('clearImportedSchedules')){const button=document.createElement('button');button.id='clearImportedSchedules';button.className='clear';button.type='button';button.textContent='Clear imported schedules';uploadRow.append(button);button.addEventListener('click',()=>{if(confirm('Clear all imported schedules from this browser?')){importedRows=[];localStorage.removeItem(IMPORTED_ROWS_KEY);applyMergedData();byId('status').textContent='Imported schedules cleared. Showing the live schedule.';}});}}
async function refreshLiveRows(){try{const response=await fetch('schedule.json?t='+Date.now(),{cache:'no-store'});if(!response.ok)throw Error('HTTP '+response.status);liveRows=normaliseRows(await response.json());showError('');applyMergedData();byId('status').textContent='Live schedule updated '+new Date().toLocaleTimeString()+(importedRows.length?' with '+importedRows.length.toLocaleString()+' imported shifts.':'.');}catch(error){showError('Live schedule could not be refreshed. Showing the last loaded schedule.');console.error('Unable to load schedule.json',error);}}
function handleUpload(event){event.stopImmediatePropagation();importScheduleFiles(event.target.files);event.target.value='';}
function handleDrop(event){event.preventDefault();event.stopImmediatePropagation();byId('drop').classList.remove('drag');importScheduleFiles(event.dataTransfer.files);}
addControls();addSafetyControls();dataSource='uploaded schedule';syncImportStatus();['search','group','period'].forEach(id=>byId(id).addEventListener('input',renderOverview));byId('date').addEventListener('input',event=>{event.stopImmediatePropagation();renderOverview();},true);byId('role').addEventListener('change',renderOverview);byId('dateView').addEventListener('change',()=>{if(byId('dateView').value&&!byId('date').value)byId('date').value=todayValue();renderOverview();});byId('clear').onclick=clearFilters;byId('emptyClear').onclick=clearFilters;byId('upload').addEventListener('change',handleUpload,true);byId('drop').addEventListener('drop',handleDrop,true);renderOverview();refreshLiveRows();setTimeout(applyMergedData,1000);setTimeout(applyMergedData,5000);setInterval(refreshLiveRows,LIVE_REFRESH_MS);
})();
