(()=>{
const IMPORTED_ROWS_KEY='scheduleImportedRows',LIVE_REFRESH_MS=60000;
let importedRows=readImportedRows(),liveRows=Array.isArray(data)?data.slice():[];
const byId=id=>document.getElementById(id);
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));}
function timeValue(value){const match=String(value||'').match(/T(\d{2}):(\d{2})/);return match?match[1]+':'+match[2]:String(value||'');}
function dateValue(value){const parts=String(value||'').split('/');return parts.length===3?parts[2]+'-'+parts[1].padStart(2,'0')+'-'+parts[0].padStart(2,'0'):String(value||'').slice(0,10);}
function todayValue(){const now=new Date();return now.getFullYear()+'-'+String(now.getMonth()+1).padStart(2,'0')+'-'+String(now.getDate()).padStart(2,'0');}
function periodValue(value){const match=String(value||'').match(/T(\d{2}):/),hour=match?Number(match[1]):0;return hour>=5&&hour<12?'AM':hour>=12&&hour<18?'PM':'Nights';}
function cleanDateTime(value){const match=String(value||'').match(/(\d{4}-\d{2}-\d{2}T\d{2}:\d{2})/);return match?match[1]:String(value||'').trim();}
function normaliseRows(rows){if(!Array.isArray(rows))throw Error('Schedule data is not a list of shifts.');return rows.filter(row=>row&&typeof row==='object').map(row=>{const location=String(row.location||'').trim(),start=cleanDateTime(row.start);return {name:String(row.name||'').trim(),location,type:String(row.type||'')||(location.toLowerCase().includes('service provider')?'CDC':'DC'),date:String(row.date||'').trim(),start,end:cleanDateTime(row.end),hours:Number(row.hours)||0,role:String(row.role||'').trim(),period:String(row.period||'')||periodValue(start)};});}
function shiftIdentity(row){return [String(row.name||'').trim().toLowerCase(),dateValue(row.date)].join('||');}
function mergeRows(...sets){const rows=new Map();sets.flat().forEach(row=>{if(row.name&&row.date)rows.set(shiftIdentity(row),row);});return [...rows.values()];}
function readImportedRows(){try{const stored=localStorage.getItem(IMPORTED_ROWS_KEY);return stored?normaliseRows(JSON.parse(stored)):[];}catch(error){console.error('Unable to read imported schedules',error);return [];}}
function saveImportedRows(rows){try{localStorage.setItem(IMPORTED_ROWS_KEY,JSON.stringify(rows));}catch(error){throw Error('Imported schedules could not be saved in this browser. Clear older imported schedules and try again.');}}
function showError(message){const error=byId('error');error.textContent=message||'';error.hidden=!message;}
function syncImportStatus(){const count=importedRows.length,clearButton=byId('clearImportedSchedules');byId('fileName').textContent=count?'schedule.json + '+count.toLocaleString()+' imported shifts':'schedule.json';if(clearButton)clearButton.disabled=!count;}
function applyMergedData(){data=mergeRows(liveRows,importedRows);setRoleOptions();syncImportStatus();renderOverview();}
function parseCsv(text){const rows=[];let row=[],cell='',quoted=false;for(let index=0;index<text.length;index++){const character=text[index],next=text[index+1];if(quoted){if(character==='"'&&next==='"'){cell+='"';index++;}else if(character==='"')quoted=false;else cell+=character;}else if(character==='"')quoted=true;else if(character===','){row.push(cell);cell='';}else if(character==='\n'){row.push(cell);rows.push(row);row=[];cell='';}else if(character!=='\r')cell+=character;}if(cell.length||row.length){row.push(cell);rows.push(row);}return rows;}
function parseUploadedCsv(text){const rows=parseCsv(text);if(!rows.length)throw Error('The file is empty.');const headers=rows[0].map(value=>String(value).replace(/^\ufeff/,'').trim().toLowerCase()),indexOf=header=>headers.indexOf(header),columns={name:indexOf('shift employee name'),location:indexOf('shift employee home location name'),date:indexOf('shift date'),start:indexOf('scheduled start time'),end:indexOf('scheduled end date'),hours:indexOf('scheduled hours'),role:headers.includes('workrole')?indexOf('workrole'):indexOf('work role')};if(Object.values(columns).some(index=>index<0))throw Error('Missing an expected schedule export column.');return rows.slice(1).filter(row=>row.some(value=>String(value).trim())).map(row=>{const location=String(row[columns.location]||'').trim(),start=cleanDateTime(row[columns.start]);return {name:String(row[columns.name]||'').trim(),location,type:location.toLowerCase().includes('service provider')?'CDC':'DC',date:String(row[columns.date]||'').trim(),start,end:cleanDateTime(row[columns.end]),hours:Number(String(row[columns.hours]||'').replace(',','.'))||0,role:String(row[columns.role]||'').trim(),period:periodValue(start)};}).filter(row=>row.name&&row.date);}
function readScheduleFile(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=event=>{try{resolve(parseUploadedCsv(event.target.result));}catch(error){reject(error);}};reader.onerror=()=>reject(Error('The browser could not read '+file.name+'.'));reader.readAsText(file);});}
async function importScheduleFiles(files){const selected=[...files].filter(file=>file&&file.name);if(!selected.length)return;try{const imported=(await Promise.all(selected.map(readScheduleFile))).flat();if(!imported.length)throw Error('The selected files contain no shifts.');const nextImported=mergeRows(importedRows,imported);saveImportedRows(nextImported);importedRows=nextImported;showError('');applyMergedData();byId('status').textContent=selected.length+' schedule file'+(selected.length===1?'':'s')+' merged. '+importedRows.length.toLocaleString()+' imported shifts available.';}catch(error){showError('Upload error: '+error.message);byId('status').textContent='The current schedule is still loaded.';}}
function dateInView(rowDate,anchor,view){if(!anchor)return true;if(view==='day'||!view)return rowDate===anchor;if(view==='month')return rowDate.slice(0,7)===anchor.slice(0,7);const date=new Date(anchor+'T00:00'),day=(date.getDay()+6)%7,start=new Date(date);start.setDate(date.getDate()-day);const end=new Date(start);end.setDate(start.getDate()+6);const startKey=start.getFullYear()+'-'+String(start.getMonth()+1).padStart(2,'0')+'-'+String(start.getDate()).padStart(2,'0'),endKey=end.getFullYear()+'-'+String(end.getMonth()+1).padStart(2,'0')+'-'+String(end.getDate()).padStart(2,'0');return rowDate>=startKey&&rowDate<=endKey;}
function baseRows(){const query=byId('search').value.trim().toLowerCase(),group=byId('group').value,date=byId('date').value,view=byId('dateView').value,roles=[...byId('role').selectedOptions].map(option=>option.value);return data.filter(row=>allowedRoles.includes(row.role)&&(!query||row.name.toLowerCase().includes(query))&&(!group||row.type===group)&&dateInView(dateValue(row.date),date,view)&&(!roles.length||roles.includes(row.role)));}
function updatePeriodOptions(){const period=byId('period'),current=period.value,rows=baseRows(),counts={AM:0,PM:0,Nights:0};rows.forEach(row=>{if(counts[row.period]!==undefined)counts[row.period]++;});period.innerHTML='<option value="">All shift patterns ('+rows.length+')</option>'+['AM','PM','Nights'].map(value=>'<option value="'+value+'">'+value+' ('+counts[value]+')</option>').join('');period.value=['','AM','PM','Nights'].includes(current)?current:'';}
function currentFilters(){const labels=[],roles=[...byId('role').selectedOptions].map(option=>option.value),view=byId('dateView').value;if(byId('search').value.trim())labels.push('name search');if(byId('group').value)labels.push(byId('group').value);if(roles.length)labels.push(roles.length===1?roles[0]:roles.length+' roles');if(byId('period').value)labels.push(byId('period').value);if(byId('date').value)labels.push(view?view+' of '+byId('date').value:byId('date').value);return labels;}
function overviewCard(row){const color=roleColors[row.role]||'default',key=encodeURIComponent([row.name,row.date,row.start,row.end,row.role].join('||')),name=escapeHtml(row.name);return '<li><article class="card card-'+color+'"><div style="display:flex;justify-content:space-between;gap:6px;align-items:flex-start"><div class="name">'+name+'</div><button class="remove-btn" type="button" data-remove="'+key+'" aria-label="Remove '+name+' from this shift">Remove</button></div><div class="role role-'+color+'">'+escapeHtml(row.role||'Work role not specified')+'</div><div class="times"><div class="time"><small>Start</small><b>'+timeValue(row.start)+'</b></div><div class="time"><small>End</small><b>'+timeValue(row.end)+'</b></div></div><div class="meta"><span>'+escapeHtml(row.period)+'</span><span>'+escapeHtml(row.hours)+' hrs</span></div></article></li>';}
function renderOverview(){updatePeriodOptions();if(typeof updateAbsenceSummary==='function')updateAbsenceSummary();const period=byId('period').value,rows=baseRows().filter(row=>!period||row.period===period).filter(row=>!removed[[row.name,row.date,row.start,row.end,row.role].join('||')]),people=new Set(rows.map(row=>row.name)),hours=rows.reduce((total,row)=>total+(Number(row.hours)||0),0),labels=currentFilters();byId('kpis').innerHTML=[['People',people.size,'indigo'],['Shift count',rows.length,'sky'],['Total hours',hours.toFixed(1),'green'],['Shift period',period||'All','violet']].map(item=>'<div class="kpi"><div class="label">'+item[0]+'</div><div class="value '+item[2]+'">'+item[1]+'</div></div>').join('');byId('count').textContent=rows.length.toLocaleString()+' shift'+(rows.length===1?'':'s');byId('cards').innerHTML=rows.slice().sort((left,right)=>String(left.start).localeCompare(String(right.start))).map(overviewCard).join('');byId('empty').hidden=Boolean(rows.length);byId('filterSummary').textContent=rows.length.toLocaleString()+' shift'+(rows.length===1?'':'s')+' for '+(labels.length?labels.join(', '):'all teams, roles, periods, and dates')+'.';byId('clear').disabled=!labels.length;}
function clearFilters(){byId('search').value='';byId('group').value='';byId('period').value='';byId('date').value='';byId('dateView').value='';[...byId('role').options].forEach(option=>option.selected=false);renderOverview();byId('search').focus();}
function addControls(){const dateField=byId('date').closest('.field'),uploadRow=byId('upload').closest('.panel').querySelector('.panel-heading');if(!byId('dateView')){const field=document.createElement('div');field.className='field';field.innerHTML='<label for="dateView">Date view</label><select id="dateView"><option value="">All scheduled dates</option><option value="day">Selected day</option><option value="week">Selected week</option><option value="month">Selected month</option></select>';dateField.insertAdjacentElement('afterend',field);}if(!byId('clearImportedSchedules')){const button=document.createElement('button');button.id='clearImportedSchedules';button.className='clear';button.type='button';button.textContent='Clear imported schedules';uploadRow.append(button);button.addEventListener('click',()=>{if(confirm('Clear all imported schedules from this browser?')){importedRows=[];localStorage.removeItem(IMPORTED_ROWS_KEY);applyMergedData();byId('status').textContent='Imported schedules cleared. Showing the live schedule.';}});}}
async function refreshLiveRows(){try{const response=await fetch('schedule.json?t='+Date.now(),{cache:'no-store'});if(!response.ok)throw Error('HTTP '+response.status);liveRows=normaliseRows(await response.json());showError('');applyMergedData();byId('status').textContent='Live schedule updated '+new Date().toLocaleTimeString()+(importedRows.length?' with '+importedRows.length.toLocaleString()+' imported shifts.':'.');}catch(error){showError('Live schedule could not be refreshed. Showing the last loaded schedule.');console.error('Unable to load schedule.json',error);}}
addControls();dataSource='uploaded schedule';syncImportStatus();['search','group','period','date'].forEach(id=>byId(id).addEventListener('input',renderOverview));byId('role').addEventListener('change',renderOverview);byId('dateView').addEventListener('change',()=>{if(byId('dateView').value&&!byId('date').value)byId('date').value=todayValue();renderOverview();});byId('clear').onclick=clearFilters;byId('emptyClear').onclick=clearFilters;byId('upload').addEventListener('change',event=>importScheduleFiles(event.target.files));byId('drop').addEventListener('drop',event=>importScheduleFiles(event.dataTransfer.files));renderOverview();refreshLiveRows();setTimeout(applyMergedData,1000);setInterval(refreshLiveRows,LIVE_REFRESH_MS);
})();
